#pragma once

#define TAPPING_TERM 175
#define PERMISSIVE_HOLD

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 600000 // 10mins
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 5000  // 5 seconds.
