include $(KEYBOARD_PATH_1)/keymaps/$(KEYMAP)/qmk-vim/rules.mk
ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
RAW_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
